const generateProperName = require("./generateProperName");

module.exports = function generateName() {
  const description = {
    adjectives: ["Bitter", "Mad", "Dynamic", "Erratic", "Fearless", "Quiet", "Respected", "Lucky", "Phantom", "Smiling", "Thunderous", "Tough", "Ungrateful", "Master", "Excessive", "Fanatical", "Intellectual", "Unlucky", "Visual", "Vulgar", "Midnight", "Mighty", "Violent", "Foolish", "Crazy", "Annoying", "Arrogant", "Golden", "Sarcastic", "Insane", "Stinky", "Drunken", "Lazy-Assed", "Amazing", "Aggressive", "Threatening ", "Philosophical", "Tough", "Sympathetic", "Brave", "Long", "Small", "Rapid", "Pinky", "Holly", "Sorrowful", "Angry", "Energising", "Wandering", "Brave", "Tame", "Well-thought-of", "Fortunate", "Unreal", "Cheerful", "Loud", "Hard", "Unpleasant", "Key", "Undue", "Rabid", "Rational", "Unfortunable", "Ocular", "Common", "Nighttime", "Powerful", "Raging", "Goosy", "Mad", "Pesky", "Chesty", "Chromatic", "Barbed", "Loopy", "Crappy", "Boozy", "Faineant", "Impressive", "Scrappy", "Minatory", "Unemotional", "Bad", "Charitable", "Heroic", "Far", "Teensy", "Fast", "Pinkie", "Blessed", "Crazy", "Slashing", "Mercurial", "Bold", "Silent", "Reputable", "Golden", "Mythic", "Twinkly", "Thundery", "Insensitive", "Thankless", "Governing", "Overweening", "Overzealous", "Noetic", "Hexed", "Visible", "Humble", "Dark", "Great", "Savage", "Dopy", "Sick", "Galling", "Proud", "Gilt", "Satiric", "Wacky", "Musty", "Bibulous", "Indolent", "Awesome", "Offtensive", "Sinister", "Philosophic", "Sturdy", "Empathetic", "Gallant", "Oblong", "Tiny", "Speedy", "Pinkish", "Dedicated", "Resentful", "Wild", "Active", "Fickle", "Hardy", "Tiptoe", "Honored", "Hot", "Illusional", "Beamish", "Deafening", "Strong", "Unappreciative", "Foremost", "Unreasonable", "Passionate", "Educated", "Luckless", "Optical", "Mean", "Sunset", "Imposing", "Hostile", "Silly", "Unhinged", "Pestering", "Self-important", "Gilded", "Sardonic", "Loco", "Niffy", "Sottish", "Slothful", "Awing", "Invasive", "Alarming", "Chilly", "Calloused", "Kind", "Spunky", "Tall", "Little", "Quick", "Chromatic", "Sanctity"],
    animals: ["Aardvark", "Albatross", "Alligator", "Alpaca", "Ant", "Anteater", "Antelope", "Ape", "Arctic Fox", "Armadillo", "Baboon", "Badger", "Barracuda", "Bat", "Beagle", "Bear", "Beaver", "Bee", "Beetle", "Bison", "Blue Whale", "Boar", "Buffalo", "Bull", "Butterfly", "Camel", "Capybara", "Caribou", "Cassowary", "Cat", "Caterpillar", "Cattle", "Chameleon", "Chamois", "Cheetah", "Chicken", "Chihuahua", "Chimpanzee", "Chinchilla", "Chinchillas", "Chough", "Cicada", "Clam", "Cobra", "Cockroach", "Cod", "Cormorant", "Cow", "Coyote", "Crab", "Crane", "Crocodile", "Crow", "Curlew", "Deer", "Dinosaur", "Dodo", "Dog", "Dogfish", "Dolphin", "Donkey", "Dotterel", "Dove", "Dragonfly", "Duck", "Dugong", "Dunlin", "Eagle", "Echidna", "Eel", "Eland", "Elephant", "Elk", "Emu", "Falcon", "Ferret", "Finch", "Fish", "Flamingo", "Fly", "Flying squirrel", "Fox", "Frog", "Gaur", "Gazelle", "Gerbil", "Giant Panda", "Giraffe", "Gnat", "Gnu", "Goat", "Goldfinch", "Goldfish", "Goose", "Gorilla", "Goshawk", "Grasshopper", "Grouse", "Guanaco", "Gull", "Hammerhead shark", "Hamster", "Hare", "Hawk", "Hedgehog", "Hen", "Hermit Crab", "Heron", "Herring", "Hippopotamus", "Hornet", "Horse", "Hummingbird", "Hyena", "Ibex", "Ibis", "Iguana", "Jackal", "Jaguar", "Jay", "Jellyfish", "Kangaroo", "Katydid", "King Cobra", "Kingfisher", "Koala", "Kookabura", "Kouprey", "Kudu", "Lapwing", "Lark", "Lemur", "Leopard", "Lion", "Lizard", "Llama", "Lobster", "Locust", "Loris", "Louse", "Lynx", "Lyrebird", "Magpie", "Mallard", "Moth", "Mammoth", "Manatee", "Mandrill", "Mantis", "Marten", "Meerkat", "Mink", "Mole", "Mongoose", "Monitor lizard", "Monkey", "Moose", "Mosquito", "Mouse", "Mule", "Narwhal", "Newt", "Nightingale", "Octopus", "Okapi", "Opossum", "Orangutan", "Oryx", "Ostrich", "Otter", "Owl", "Oyster", "Panther", "Parrot", "Partridge", "Peacock", "Peafowl", "Pelican", "Penguin", "Pheasant", "Pig", "Pigeon", "Polar bear", "Pony", "Porcupine", "Porpoise", "Possum", "Quail", "Quelea", "Quetzal", "Rabbit", "Raccoon", "Racoon", "Ram", "Rat", "Raven", "Red deer", "Red panda", "Reindeer", "Rhinoceros", "Rook", "Salamander", "Salmon", "Sand Dollar", "Sandpiper", "Sardine", "Scorpion", "Seahorse", "Seal", "Shark", "Sheep", "Shrew", "Skunk", "Sloth", "Snail", "Snake", "Sparrow", "Spider", "Spoonbill", "Squid", "Squirrel", "Starling", "Stingray", "Stinkbug", "Stork", "Swallow", "Swan", "Tapir", "Tarsier", "Termite", "Tiger", "Toad", "Tortoise", "Trout", "Turkey", "Turtle", "Viper", "Vulture", "Wallaby", "Walrus", "Wasp", "Weasel", "Whale", "Wildcat", "Wolf", "Wolverine", "Wombat", "Woodcock", "Woodpecker", "Worm", "Wren", "Yak", "Zebra"],
  };
  // generate proper name
  const properName = generateProperName();
  // random adjective
  const randomAdjective = description.adjectives[Math.floor(Math.random() * description.adjectives.length)];
  // random animal
  const randomAnimal = description.animals[Math.floor(Math.random() * description.animals.length)];
  return `${properName} the ${randomAdjective} ${randomAnimal}`;
};
