module.exports = function generateName() {
  const description = {
    adjectives: ["Bitter", "Mad", "Dynamic", "Erratic", "Fearless", "Quiet", "Respected", "Lucky", "Phantom", "Smiling", "Thunderous", "Tough", "Ungrateful", "Master", "Excessive", "Fanatical", "Intellectual", "Unlucky", "Visual", "Vulgar", "Midnight", "Mighty", "Violent", "Foolish", "Crazy", "Annoying", "Arrogant", "Golden", "Sarcastic", "Insane", "Stinky", "Drunken", "Lazy-Assed", "Amazing", "Aggressive", "Threatening ", "Philosophical", "Tough", "Sympathetic", "Brave", "Long", "Small", "Rapid", "Pinky", "Holly", "Sorrowful", "Angry", "Energising", "Wandering", "Brave", "Tame", "Well-thought-of", "Fortunate", "Unreal", "Cheerful", "Loud", "Hard", "Unpleasant", "Key", "Undue", "Rabid", "Rational", "Unfortunable", "Ocular", "Common", "Nighttime", "Powerful", "Raging", "Goosy", "Mad", "Pesky", "Chesty", "Chromatic", "Barbed", "Loopy", "Crappy", "Boozy", "Faineant", "Impressive", "Scrappy", "Minatory", "Unemotional", "Bad", "Charitable", "Heroic", "Far", "Teensy", "Fast", "Pinkie", "Blessed", "Crazy", "Slashing", "Mercurial", "Bold", "Silent", "Reputable", "Golden", "Mythic", "Twinkly", "Thundery", "Insensitive", "Thankless", "Governing", "Overweening", "Overzealous", "Noetic", "Hexed", "Visible", "Humble", "Dark", "Great", "Savage", "Dopy", "Sick", "Galling", "Proud", "Gilt", "Satiric", "Wacky", "Musty", "Bibulous", "Indolent", "Awesome", "Offtensive", "Sinister", "Philosophic", "Sturdy", "Empathetic", "Gallant", "Oblong", "Tiny", "Speedy", "Pinkish", "Dedicated", "Resentful", "Wild", "Active", "Fickle", "Hardy", "Tiptoe", "Honored", "Hot", "Illusional", "Beamish", "Deafening", "Strong", "Unappreciative", "Foremost", "Unreasonable", "Passionate", "Educated", "Luckless", "Optical", "Mean", "Sunset", "Imposing", "Hostile", "Silly", "Unhinged", "Pestering", "Self-important", "Gilded", "Sardonic", "Loco", "Niffy", "Sottish", "Slothful", "Awing", "Invasive", "Alarming", "Chilly", "Calloused", "Kind", "Spunky", "Tall", "Little", "Quick", "Chromatic", "Sanctity"],
    animals: ["Aardvark", "Albatross", "Alligator", "Alpaca", "Ant", "Anteater", "Antelope", "Ape", "Arctic fox", "Armadillo", "Baboon", "Badger", "Barracuda", "Bat", "Beagle", "Bear", "Beaver", "Bee", "Bison", "Blue Whale", "Boar", "Buffalo", "Bull", "Butterfly", "Camel", "Capybara", "Caribou", "Cassowary", "Cat", "Caterpillar", "Cattle", "Chameleon", "Chamois", "Cheetah", "Chicken", "Chihuahua", "Chimpanzee", "Chinchilla", "Chinchillas", "Chough", "Clam", "Cobra", "Cockroach", "Cod", "Cormorant", "Cow", "Coyote", "Crab", "Crane", "Crocodile", "Crow", "Curlew", "Deer", "Dinosaur", "Dodo", "Dog", "Dogfish", "Dolphin", "Donkey", "Dotterel", "Dove", "Dragonfly", "Duck", "Dugong", "Dunlin", "Eagle", "Echidna", "Eel", "Eland", "Elephant", "Elk", "Emu", "Falcon", "Ferret", "Finch", "Fish", "Flamingo", "Fly", "Flying squirrel", "Fox", "Frog", "Gaur", "Gazelle", "Gerbil", "Giant Panda", "Giraffe", "Gnat", "Gnu", "Goat", "Goldfinch", "Goldfish", "Goose", "Gorilla", "Goshawk", "Grasshopper", "Grouse", "Guanaco", "Gull", "Hammerhead shark", "Hamster", "Hare", "Hawk", "Hedgehog", "Hen", "Hermit Crab", "Heron", "Herring", "Hippopotamus", "Hornet", "Horse", "Hummingbird", "Hyena", "Ibex", "Ibis", "Iguana", "Jackal", "Jaguar", "Jay", "Jellyfish", "Kangaroo", "King Cobra", "Kingfisher", "Koala", "Kookabura", "Kouprey", "Kudu", "Lapwing", "Lark", "Lemur", "Leopard", "Lion", "Lizard", "Llama", "Lobster", "Locust", "Loris", "Louse", "Lynx", "Lyrebird", "Magpie", "Mallard", "Mammoth", "Manatee", "Mandrill", "Mantis", "Marten", "Meerkat", "Mink", "Mole", "Mongoose", "Monitor lizard", "Monkey", "Moose", "Mosquito", "Mouse", "Mule", "Narwhal", "Newt", "Nightingale", "Octopus", "Okapi", "Opossum", "Orangutan", "Oryx", "Ostrich", "Otter", "Owl", "Oyster", "Panther", "Parrot", "Partridge", "Peacock", "Peafowl", "Pelican", "Penguin", "Pheasant", "Pig", "Pigeon", "Polar bear", "Pony", "Porcupine", "Porpoise", "Possum", "Quail", "Quelea", "Quetzal", "Rabbit", "Raccoon", "Racoon", "Ram", "Rat", "Raven", "Red deer", "Red panda", "Reindeer", "Rhinoceros", "Rook", "Salamander", "Salmon", "Sand Dollar", "Sandpiper", "Sardine", "Scorpion", "Seahorse", "Seal", "Shark", "Sheep", "Shrew", "Skunk", "Sloth", "Snail", "Snake", "Sparrow", "Spider", "Spoonbill", "Squid", "Squirrel", "Starling", "Stingray", "Stinkbug", "Stork", "Swallow", "Swan", "Tapir", "Tarsier", "Termite", "Tiger", "Toad", "Tortoise", "Trout", "Turkey", "Turtle", "Viper", "Vulture", "Wallaby", "Walrus", "Wasp", "Weasel", "Whale", "Wildcat", "Wolf", "Wolverine", "Wombat", "Woodcock", "Woodpecker", "Worm", "Wren", "Yak", "Zebra"],
  };

  var nm1 = ["a", "e", "i", "o", "u"];
  var nm2 = ["", "", "", "c", "cr", "d", "dh", "dr", "g", "gr", "j", "k", "kr", "kh", "p", "pr", "q", "qr", "r", "rh", "sh", "st", "str", "t", "th", "tr", "v", "vr", "w", "x", "z"];
  var nm3 = ["a", "e", "i", "o", "u", "a", "e", "i", "o", "u"];
  var nm4 = ["d", "g", "l", "n", "r", "v", "z", "d", "g", "l", "n", "r", "v", "z", "d", "dr", "g", "gr", "l", "lr", "lv", "lz", "n", "nd", "nv", "nz", "r", "rl", "v", "z"];
  var nm5 = ["bahn", "barin", "beus", "bin", "bras", "bus", "dalf", "darin", "del", "dium", "dius", "dor", "dore", "dus", "farihm", "faris", "feus", "flyn", "forn", "gast", "geor", "gorim", "gron", "grus", "hagan", "harad", "haris", "hith", "hone", "jahr", "jamar", "kalis", "key", "kius", "kore", "kron", "ldor", "lenor", "leus", "lin", "lius", "lore", "maex", "marim", "mazz", "monar", "morn", "naxx", "neth", "neus", "nior", "nitor", "norim", "pan", "phiar", "phior", "pius", "prix", "qihr", "qiohr", "qirax", "qium", "qor", "quam", "ras", "rhan", "rick", "rius", "rnas", "ronin", "rune", "shan", "sim", "sior", "sorin", "strum", "tarum", "taz", "thar", "tior", "torn", "trix", "veus", "viar", "vior", "vius", "vras", "wix", "wyn", "xar", "xeor", "xium", "xius", "xon", "zahl", "zahr", "zax", "zin", "zohr", "zor"];
  var nm6 = ["", "", "", "", "", "c", "ch", "d", "f", "fr", "h", "l", "m", "n", "ph", "q", "r", "rh", "s", "sh", "th", "v", "z"];
  var nm7 = ["d", "h", "l", "ll", "m", "mn", "n", "nn", "ph", "r", "s", "t", "z"];
  var nm8 = ["baris", "belle", "bess", "bine", "bis", "dali", "deis", "delis", "dores", "drisse", "dyora", "dyrin", "ffaeh", "faris", "ffea", "fora", "fyne", "gaell", "ganis", "ghis", "goris", "greth", "haen", "harise", "harith", "hione", "hith", "khealis", "kely", "key", "kon", "kora", "llaes", "lleas", "less", "lore", "lune", "lyn", "lyna", "maev", "mari", "menazz", "monora", "morith", "naxis", "nneas", "nelle", "ni", "nilorh", "nora", "nydae", "nyll", "phaen", "phi", "phiane", "phior", "phyx", "pianne", "prixy", "qia", "qille", "qinn", "qiohne", "qora", "rass", "rihann", "rish", "ro", "rune", "ssaem", "shann", "sinore", "sophi", "strea", "tarish", "tazz", "thall", "tiye", "tosh", "trixi", "vae", "via", "vile", "vira", "vys", "waelle", "weahl", "wixe", "wyss", "wyn", "xaryl", "xea", "xis", "xone", "xyll", "zahne", "zith", "zohra", "zora", "zyni"];
  var nm9 = ["barin", "baris", "bin", "bine", "bis", "bras", "dall", "dali", "darin", "deis", "del", "delis", "dor", "dyrin", "farih", "ffaeh", "ffyn", "gaell", "ghis", "gorin", "goris", "greth", "haen", "haris", "harith", "hion", "hith", "kalis", "kelis", "key", "kias", "konn", "kore", "karon", "ldor", "lenor", "less", "lin", "llaes", "lleas", "lore", "lyn", "mal", "mari", "monar", "morith", "nell", "neth", "neas", "ni", "nilorh", "nior", "nneas", "noran", "norim", "nyll", "pan", "phiar", "phior", "prix", "qihr", "qill", "qinn", "qiohn", "qor", "ras", "rass", "rhan", "rihann", "rish", "rias", "rnas", "ro", "ronin", "rin", "shan", "shann", "sim", "sior", "sorin", "ssaem", "strea", "tarish", "thall", "tior", "tosh", "trix", "veus", "viar", "vior", "vius", "vys", "wyn", "wyss", "xyll", "zahl", "zin", "zith", "zohr", "zor"];

  const rnd = (Math.random() * nm1.length) | 0;
  const rnd2 = (Math.random() * nm7.length) | 0;
  const rnd5 = (Math.random() * nm3.length) | 0;
  const rnd6 = (Math.random() * nm8.length) | 0;
  const name = nm1[rnd] + nm7[rnd2] + nm3[rnd5] + nm8[rnd6];
  const properName = name.charAt(0).toUpperCase() + name.slice(1);

  // random adjective
  const randomAdjective = description.adjectives[Math.floor(Math.random() * description.adjectives.length)];
  // random animal
  const randomAnimal = description.animals[Math.floor(Math.random() * description.animals.length)];
  return `${properName} the ${randomAdjective} ${randomAnimal}`;
};
